[2024-10-04T17:11:59.118+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T17:11:59.181+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_json_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T17:11:59.203+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_json_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T17:11:59.206+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-04T17:11:59.239+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): call_api_task> on 2024-10-03 00:00:00+00:00
[2024-10-04T17:11:59.250+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1739) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-04T17:11:59.253+0000] {standard_task_runner.py:64} INFO - Started process 1747 to run task
[2024-10-04T17:11:59.250+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'api_to_json_dag', 'call_api_task', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/dag_to_api.py', '--cfg-path', '/tmp/tmp5vznrxf2']
[2024-10-04T17:11:59.255+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask call_api_task
[2024-10-04T17:11:59.294+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T17:11:59.381+0000] {task_command.py:426} INFO - Running <TaskInstance: api_to_json_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [running]> on host 3fed06331d8d
[2024-10-04T17:11:59.586+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_json_dag' AIRFLOW_CTX_TASK_ID='call_api_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T17:11:59.588+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T17:11:59.869+0000] {logging_mixin.py:188} INFO - File api_data.json đã được tạo thành công.
[2024-10-04T17:11:59.871+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-04T17:11:59.873+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T17:11:59.894+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=api_to_json_dag, task_id=call_api_task, run_id=scheduled__2024-10-03T00:00:00+00:00, execution_date=20241003T000000, start_date=20241004T171159, end_date=20241004T171159
[2024-10-04T17:11:59.954+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-04T17:11:59.989+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-04T17:11:59.997+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-04T17:14:10.248+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T17:14:10.338+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_json_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T17:14:10.382+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_json_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T17:14:10.383+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-04T17:14:10.438+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): call_api_task> on 2024-10-03 00:00:00+00:00
[2024-10-04T17:14:10.450+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1921) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-04T17:14:10.452+0000] {standard_task_runner.py:64} INFO - Started process 1924 to run task
[2024-10-04T17:14:10.450+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'api_to_json_dag', 'call_api_task', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/dag_to_api.py', '--cfg-path', '/tmp/tmp7ewfc_ay']
[2024-10-04T17:14:10.454+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask call_api_task
[2024-10-04T17:14:10.490+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T17:14:10.580+0000] {task_command.py:426} INFO - Running <TaskInstance: api_to_json_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [running]> on host 3fed06331d8d
[2024-10-04T17:14:10.798+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_json_dag' AIRFLOW_CTX_TASK_ID='call_api_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T17:14:10.800+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T17:14:10.846+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-04T17:14:10.849+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python call_api.py']
[2024-10-04T17:14:10.868+0000] {subprocess.py:86} INFO - Output:
[2024-10-04T17:14:10.913+0000] {subprocess.py:93} INFO - python: can't open file '/tmp/***tmps58z0_s2/call_api.py': [Errno 2] No such file or directory
[2024-10-04T17:14:10.922+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-10-04T17:14:10.927+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T17:14:10.958+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-10-04T17:14:10.974+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=api_to_json_dag, task_id=call_api_task, run_id=scheduled__2024-10-03T00:00:00+00:00, execution_date=20241003T000000, start_date=20241004T171410, end_date=20241004T171410
[2024-10-04T17:14:11.021+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 50 for task call_api_task (Bash command failed. The command returned a non-zero exit code 2.; 1924)
[2024-10-04T17:14:11.072+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-04T17:14:11.098+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-04T17:23:53.356+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T17:23:53.414+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_json_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T17:23:53.434+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_json_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T17:23:53.436+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-04T17:23:53.469+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): call_api_task> on 2024-10-03 00:00:00+00:00
[2024-10-04T17:23:53.481+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=2701) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-04T17:23:53.484+0000] {standard_task_runner.py:64} INFO - Started process 2704 to run task
[2024-10-04T17:23:53.481+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'api_to_json_dag', 'call_api_task', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/dag_to_api.py', '--cfg-path', '/tmp/tmp_226hce8']
[2024-10-04T17:23:53.487+0000] {standard_task_runner.py:91} INFO - Job 52: Subtask call_api_task
[2024-10-04T17:23:53.524+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T17:23:53.603+0000] {task_command.py:426} INFO - Running <TaskInstance: api_to_json_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [running]> on host 3fed06331d8d
[2024-10-04T17:23:53.786+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_json_dag' AIRFLOW_CTX_TASK_ID='call_api_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T17:23:53.787+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T17:23:54.040+0000] {logging_mixin.py:188} INFO - File api_data.json đã được tạo thành công.
[2024-10-04T17:23:54.042+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-04T17:23:54.044+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T17:23:54.068+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=api_to_json_dag, task_id=call_api_task, run_id=scheduled__2024-10-03T00:00:00+00:00, execution_date=20241003T000000, start_date=20241004T172353, end_date=20241004T172354
[2024-10-04T17:23:54.145+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-04T17:23:54.188+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-04T17:23:54.195+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-04T17:33:55.192+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T17:33:55.259+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_json_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T17:33:55.282+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_json_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T17:33:55.284+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-04T17:33:55.318+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): call_api_task> on 2024-10-03 00:00:00+00:00
[2024-10-04T17:33:55.330+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=3521) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-04T17:33:55.333+0000] {standard_task_runner.py:64} INFO - Started process 3522 to run task
[2024-10-04T17:33:55.330+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'api_to_json_dag', 'call_api_task', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dag_to_api.py', '--cfg-path', '/tmp/tmpl5h49zdi']
[2024-10-04T17:33:55.335+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask call_api_task
[2024-10-04T17:33:55.378+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T17:33:55.463+0000] {task_command.py:426} INFO - Running <TaskInstance: api_to_json_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [running]> on host 3fed06331d8d
[2024-10-04T17:33:55.674+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_json_dag' AIRFLOW_CTX_TASK_ID='call_api_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T17:33:55.676+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T17:33:55.917+0000] {logging_mixin.py:188} INFO - File dagspi_data.json đã được tạo thành công.
[2024-10-04T17:33:55.921+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-04T17:33:55.926+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T17:33:55.977+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=api_to_json_dag, task_id=call_api_task, run_id=scheduled__2024-10-03T00:00:00+00:00, execution_date=20241003T000000, start_date=20241004T173355, end_date=20241004T173355
[2024-10-04T17:33:56.034+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-04T17:33:56.096+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-04T17:33:56.107+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-04T17:41:33.092+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T17:41:33.156+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_json_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T17:41:33.177+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_json_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T17:41:33.179+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-04T17:41:33.216+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): call_api_task> on 2024-10-03 00:00:00+00:00
[2024-10-04T17:41:33.227+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=4122) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-04T17:41:33.229+0000] {standard_task_runner.py:64} INFO - Started process 4123 to run task
[2024-10-04T17:41:33.227+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'api_to_json_dag', 'call_api_task', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dag_to_api.py', '--cfg-path', '/tmp/tmpf_5aucuu']
[2024-10-04T17:41:33.231+0000] {standard_task_runner.py:91} INFO - Job 54: Subtask call_api_task
[2024-10-04T17:41:33.268+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T17:41:33.345+0000] {task_command.py:426} INFO - Running <TaskInstance: api_to_json_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [running]> on host 3fed06331d8d
[2024-10-04T17:41:33.526+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_json_dag' AIRFLOW_CTX_TASK_ID='call_api_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T17:41:33.528+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T17:41:33.801+0000] {logging_mixin.py:188} INFO - File dagspi_data.json đã được tạo thành công.
[2024-10-04T17:41:33.804+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-04T17:41:33.806+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T17:41:33.828+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=api_to_json_dag, task_id=call_api_task, run_id=scheduled__2024-10-03T00:00:00+00:00, execution_date=20241003T000000, start_date=20241004T174133, end_date=20241004T174133
[2024-10-04T17:41:33.891+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-04T17:41:33.926+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-04T17:41:33.936+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
