[2024-10-04T15:22:05.113+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T15:22:05.162+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T15:22:05.190+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T15:22:05.192+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-04T15:22:05.234+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): call_api_task> on 2024-10-03 00:00:00+00:00
[2024-10-04T15:22:05.248+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1937) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-04T15:22:05.250+0000] {standard_task_runner.py:64} INFO - Started process 1938 to run task
[2024-10-04T15:22:05.248+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_api_call_dag', 'call_api_task', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dag_to_api.py', '--cfg-path', '/tmp/tmpt5ym4ytd']
[2024-10-04T15:22:05.253+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask call_api_task
[2024-10-04T15:22:05.293+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T15:22:05.368+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [running]> on host 3fed06331d8d
[2024-10-04T15:22:05.565+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_api_call_dag' AIRFLOW_CTX_TASK_ID='call_api_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T15:22:05.567+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T15:22:05.936+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-04T15:22:05.939+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T15:22:05.965+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=minio_api_call_dag, task_id=call_api_task, run_id=scheduled__2024-10-03T00:00:00+00:00, execution_date=20241003T000000, start_date=20241004T152205, end_date=20241004T152205
[2024-10-04T15:22:06.034+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-04T15:22:06.102+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-04T15:22:06.112+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-04T15:27:12.088+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T15:27:12.124+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T15:27:12.143+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T15:27:12.144+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-04T15:27:12.181+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): call_api_task> on 2024-10-03 00:00:00+00:00
[2024-10-04T15:27:12.193+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=2346) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-04T15:27:12.196+0000] {standard_task_runner.py:64} INFO - Started process 2347 to run task
[2024-10-04T15:27:12.193+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_api_call_dag', 'call_api_task', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dag_to_api.py', '--cfg-path', '/tmp/tmpygcnsxjo']
[2024-10-04T15:27:12.198+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask call_api_task
[2024-10-04T15:27:12.230+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T15:27:12.304+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [running]> on host 3fed06331d8d
[2024-10-04T15:27:12.485+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_api_call_dag' AIRFLOW_CTX_TASK_ID='call_api_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T15:27:12.487+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T15:27:12.741+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-04T15:27:12.743+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T15:27:12.760+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=minio_api_call_dag, task_id=call_api_task, run_id=scheduled__2024-10-03T00:00:00+00:00, execution_date=20241003T000000, start_date=20241004T152712, end_date=20241004T152712
[2024-10-04T15:27:12.817+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-04T15:27:12.857+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-04T15:27:12.865+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-04T15:44:16.401+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T15:44:16.439+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T15:44:16.458+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T15:44:16.460+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-04T15:44:16.496+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): call_api_task> on 2024-10-03 00:00:00+00:00
[2024-10-04T15:44:16.508+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=3745) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-04T15:44:16.510+0000] {standard_task_runner.py:64} INFO - Started process 3746 to run task
[2024-10-04T15:44:16.508+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_api_call_dag', 'call_api_task', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dag_to_api.py', '--cfg-path', '/tmp/tmp8nhtm0yw']
[2024-10-04T15:44:16.513+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask call_api_task
[2024-10-04T15:44:16.545+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T15:44:16.619+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [running]> on host 3fed06331d8d
[2024-10-04T15:44:16.806+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_api_call_dag' AIRFLOW_CTX_TASK_ID='call_api_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T15:44:16.810+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T15:44:17.093+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-04T15:44:17.096+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T15:44:17.118+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=minio_api_call_dag, task_id=call_api_task, run_id=scheduled__2024-10-03T00:00:00+00:00, execution_date=20241003T000000, start_date=20241004T154416, end_date=20241004T154417
[2024-10-04T15:44:17.171+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-04T15:44:17.218+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-04T15:44:17.226+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-04T16:25:25.334+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T16:25:25.370+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T16:25:25.389+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T16:25:25.390+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-04T16:25:25.426+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): call_api_task> on 2024-10-03 00:00:00+00:00
[2024-10-04T16:25:25.448+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=7084) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-04T16:25:25.450+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_api_call_dag', 'call_api_task', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/dag_to_api.py', '--cfg-path', '/tmp/tmpaxd8nirx']
[2024-10-04T16:25:25.456+0000] {standard_task_runner.py:64} INFO - Started process 7085 to run task
[2024-10-04T16:25:25.459+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask call_api_task
[2024-10-04T16:25:25.513+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T16:25:25.596+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [running]> on host 3fed06331d8d
[2024-10-04T16:25:25.813+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_api_call_dag' AIRFLOW_CTX_TASK_ID='call_api_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T16:25:25.815+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T16:25:26.078+0000] {logging_mixin.py:188} INFO - File api_data.json đã được tạo thành công.
[2024-10-04T16:25:26.080+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-04T16:25:26.083+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T16:25:26.101+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=minio_api_call_dag, task_id=call_api_task, run_id=scheduled__2024-10-03T00:00:00+00:00, execution_date=20241003T000000, start_date=20241004T162525, end_date=20241004T162526
[2024-10-04T16:25:26.166+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-04T16:25:26.212+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-04T16:25:26.219+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-04T16:38:32.912+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T16:38:32.959+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T16:38:32.979+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T16:38:32.980+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-04T16:38:33.038+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): call_api_task> on 2024-10-03 00:00:00+00:00
[2024-10-04T16:38:33.051+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_api_call_dag', 'call_api_task', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/dag_to_api.py', '--cfg-path', '/tmp/tmpv5lewt1x']
[2024-10-04T16:38:33.052+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=8145) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-04T16:38:33.059+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask call_api_task
[2024-10-04T16:38:33.060+0000] {standard_task_runner.py:64} INFO - Started process 8153 to run task
[2024-10-04T16:38:33.107+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T16:38:33.274+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [running]> on host 3fed06331d8d
[2024-10-04T16:38:33.586+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_api_call_dag' AIRFLOW_CTX_TASK_ID='call_api_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T16:38:33.592+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T16:38:33.912+0000] {logging_mixin.py:188} INFO - File api_data.json đã được tạo thành công.
[2024-10-04T16:38:33.915+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-04T16:38:33.917+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T16:38:33.949+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=minio_api_call_dag, task_id=call_api_task, run_id=scheduled__2024-10-03T00:00:00+00:00, execution_date=20241003T000000, start_date=20241004T163832, end_date=20241004T163833
[2024-10-04T16:38:34.058+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-04T16:38:34.212+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-04T16:38:34.281+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-04T16:45:39.006+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T16:45:39.044+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T16:45:39.063+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T16:45:39.065+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-04T16:45:39.101+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): call_api_task> on 2024-10-03 00:00:00+00:00
[2024-10-04T16:45:39.115+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_api_call_dag', 'call_api_task', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/dag_to_api.py', '--cfg-path', '/tmp/tmpsmhpgqv5']
[2024-10-04T16:45:39.121+0000] {standard_task_runner.py:91} INFO - Job 43: Subtask call_api_task
[2024-10-04T16:45:39.115+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=8728) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-04T16:45:39.128+0000] {standard_task_runner.py:64} INFO - Started process 8729 to run task
[2024-10-04T16:45:39.211+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T16:45:39.315+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [running]> on host 3fed06331d8d
[2024-10-04T16:45:39.538+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_api_call_dag' AIRFLOW_CTX_TASK_ID='call_api_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T16:45:39.540+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T16:45:39.794+0000] {logging_mixin.py:188} INFO - File C:\Users\ADMIN\Downloads\Documents\setup_***\dags\api_data.json đã được tạo thành công trên máy local.
[2024-10-04T16:45:39.798+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-04T16:45:39.810+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T16:45:39.852+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=minio_api_call_dag, task_id=call_api_task, run_id=scheduled__2024-10-03T00:00:00+00:00, execution_date=20241003T000000, start_date=20241004T164539, end_date=20241004T164539
[2024-10-04T16:45:39.922+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-04T16:45:39.976+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-04T16:45:39.984+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-04T16:53:25.970+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T16:53:26.010+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T16:53:26.031+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T16:53:26.033+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-04T16:53:26.067+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): call_api_task> on 2024-10-03 00:00:00+00:00
[2024-10-04T16:53:26.080+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=275) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-04T16:53:26.080+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_api_call_dag', 'call_api_task', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/dag_to_api.py', '--cfg-path', '/tmp/tmpv88174z0']
[2024-10-04T16:53:26.083+0000] {standard_task_runner.py:64} INFO - Started process 276 to run task
[2024-10-04T16:53:26.085+0000] {standard_task_runner.py:91} INFO - Job 47: Subtask call_api_task
[2024-10-04T16:53:26.121+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T16:53:26.198+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [running]> on host 3fed06331d8d
[2024-10-04T16:53:26.379+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_api_call_dag' AIRFLOW_CTX_TASK_ID='call_api_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T16:53:26.382+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T16:53:26.619+0000] {logging_mixin.py:188} INFO - File C:\Users\ADMIN\Downloads\Documents\setup_***\dags\api_data.json đã được tạo thành công trên máy local.
[2024-10-04T16:53:26.621+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-04T16:53:26.623+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T16:53:26.640+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=minio_api_call_dag, task_id=call_api_task, run_id=scheduled__2024-10-03T00:00:00+00:00, execution_date=20241003T000000, start_date=20241004T165326, end_date=20241004T165326
[2024-10-04T16:53:26.704+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-04T16:53:26.736+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-04T16:53:26.746+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-04T16:59:41.172+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T16:59:41.216+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T16:59:41.240+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T16:59:41.241+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-04T16:59:41.291+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): call_api_task> on 2024-10-03 00:00:00+00:00
[2024-10-04T16:59:41.306+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=765) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-04T16:59:41.309+0000] {standard_task_runner.py:64} INFO - Started process 766 to run task
[2024-10-04T16:59:41.306+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_api_call_dag', 'call_api_task', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/dag_to_api.py', '--cfg-path', '/tmp/tmpyyx1s0fq']
[2024-10-04T16:59:41.312+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask call_api_task
[2024-10-04T16:59:41.353+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T16:59:41.425+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_api_call_dag.call_api_task scheduled__2024-10-03T00:00:00+00:00 [running]> on host 3fed06331d8d
[2024-10-04T16:59:41.598+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_api_call_dag' AIRFLOW_CTX_TASK_ID='call_api_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T16:59:41.600+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T16:59:41.853+0000] {logging_mixin.py:188} INFO - File C:\Users\ADMIN\Downloads\Documents\setup_***\dags\api_data.json đã được tạo thành công trên máy local.
[2024-10-04T16:59:41.855+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-04T16:59:41.856+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T16:59:41.874+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=minio_api_call_dag, task_id=call_api_task, run_id=scheduled__2024-10-03T00:00:00+00:00, execution_date=20241003T000000, start_date=20241004T165941, end_date=20241004T165941
[2024-10-04T16:59:41.926+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-04T16:59:41.966+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-04T16:59:41.973+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
